#!/bin/bash
if [[ $# -eq 0 ]]; then
    echo -e "usage:"
    echo -e "\t search: $(basename $0) <WORD> ..."
    echo -e "\t remove: $(basename $0) -r <WORD> ..."
    echo -e "\t memory: $(basename $0) -l [N]"
    exit 0
fi

hf=~/.fanyi_history
dir=~/.fanyi
remove=false

if [[ $1 == '-l' ]]; then
	shift
	n=${1:-3}
	words=($(cat $hf))
	for((i=0;i<n;++i)); do
		index=$((RANDOM % ${#words[*]}))
		$0 ${words[$index]}
	done
	exit $?
fi

if [[ $1 == "-r" ]]; then
    remove=true
    shift
fi

query() {
node <<EOFXXX
function add(a, b) {
	if(a.indexOf(b) < 0) {
		a.push(b);
	}
}

try {
	let result=$(curl -0 -s "http://www.iciba.com/index.php?a=getWordMean&c=search&list=1%2C2%2C3%2C4%2C5%2C8%2C9%2C10%2C12%2C13%2C14%2C15%2C18%2C21%2C22%2C24%2C3003%2C3004%2C3005&word=$1");
	
	if(result.baesInfo && result.baesInfo.symbols && result.baesInfo.symbols[0]) {
		let ph_en = result.baesInfo.symbols[0].ph_en;
		let ph_am = result.baesInfo.symbols[0].ph_am;
		console.log(\`英 [\${ph_en}], 美 [\${ph_am}]\`);
		
		result.baesInfo.symbols[0].parts.map((e) => { console.log(\`\${e.part} \${e.means.join('； ')}\`); });
		console.log('');
	}
	
	let ex = [];
	
	if(result.collins) {
		for(let i = 0; i < result.collins.length; ++ i) { 
			let entry = result.collins[i].entry;
			for(let j = 0; j < entry.length; ++ j) {
				for(let k = 0; k < entry[j].example.length; ++ k) {
					add(ex, entry[j].example[k].ex);
				}
	        }
	    }
	}
	
	if(result.sentence) {
	    let sentence = result.sentence;
	    for(let i = 0; i < sentence.length; ++ i) {
	        add(ex, sentence[i].Network_en);
	    }
	}
	
	ex = ex.slice(0, 5);
	for(let i = 0; i < ex.length; ++ i) {
	    console.log(\`\${i+1}\t\${ex[i]}\`);
	}
} catch(e) {}
EOFXXX
}

translate() {
    word=${1,,} 
    if [[ -f $dir/$word ]]; then
        cat $dir/$word
        exit 0
    fi

    mkdir -p $dir
	result=$(query $word)
	if [[ -n "$result" ]]; then
		echo "$result" | tee $dir/$word
	fi
}

for word in $*; do
    word=${word,,}
    if $remove; then
        sed -r -i "/^$word$/ d" $hf
        rm -f $dir/$word
    else
        echo $word:
        result=$(translate $word)
        if [[ -n $result ]]; then
            while read -r line; do
                echo -e "\t$line"
            done < <(echo "$result")
    
            if [[ ! -f $hf ]] || ! grep "^$word$" $hf > /dev/null; then # save to history
                echo $word >> $hf
            fi
        fi
        echo
    fi
done 
